@echo off
echo Syncing to Capacitor...
npx cap sync
echo Copying to Android assets...
copy /Y www\index.html android\app\src\main\assets\public\index.html
echo Verifying...
findstr "cueSelect_correct" android\app\src\main\assets\public\index.html
echo Done! Hit Run in Android Studio, then clear cache on phone.