@echo off
echo Pulling latest from GitHub...
git pull
echo Building JS bundle...
npm run build
echo Copying Sonoro.html to www...
del /F www\index.html
copy /Y Sonoro.html www\index.html
echo Syncing to Capacitor...
npx cap sync
npx cap sync android
echo Done! Hit Run in Android Studio, then clear app cache on phone.