@echo off
echo Pulling latest from GitHub...
git pull
echo Building JS bundle...
npm run build
echo Removing Vite-generated index.html...
del /F www\index.html
echo Copying Sonoro.html as index.html...
copy /Y Sonoro.html www\index.html
echo Syncing to Capacitor...
npx cap sync
echo Done!