@echo off
echo Pulling from GitHub...
git pull
echo Building JS bundle...
npm run build || echo Build step done.
echo Copying Sonoro.html to www...
del /F www\index.html
copy /Y Sonoro.html www\index.html
echo Syncing Capacitor...
npx cap sync
echo Copying to Android assets...
copy /Y www\index.html android\app\src\main\assets\public\index.html
echo Done! Hit Run in Android Studio, then clear cache on phone.